celery_django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

todolist/urls.py
from django.urls import path
from . import views

app_name = "todolist"

urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.add, name="add"),
    path('<int:id>/delete', views.delete, name="delete")
]

todolist/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    content = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.content}"

todolist/forms.py
from django import forms
from django.utils.safestring import mark_safe
from todolist.models import Todo

class AddForm(forms.ModelForm):
    content = forms.CharField(
        label=mark_safe("<strong>Content</strong>"),
        min_length=5,
        max_length=255,
        widget=forms.TextInput
        (attrs={'class':'form-control',
            'placeholder':'Create an awesome thing'
        }))

    class Meta:
        model = Todo
        fields = ["content"]

todolist/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect

from todolist.models import Todo
from todolist.forms import AddForm
from todolist import tasks

# Create your views here.

def index(request):
    todos = Todo.objects.all()
    return render(request, "todolist/index.html", {
        "todos": todos,
    })

def add(request):
    todos = Todo.objects.all()
    if request.method == "POST":
        form = AddForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            tasks.add.delay(data.content)
            return HttpResponseRedirect(reverse('todolist:index'))
        else:
            return render(request, "todolist/add.html", {
            "addForm": AddForm()
            })

    else:
        return render(request, "todolist/add.html", {
            "addForm": AddForm()
        })

def delete(request, id):
    tasks.remove.delay(id)
    return HttpResponseRedirect(reverse('todolist:index'))

todolist/templates/todolist/add.html
{% extends "todolist/layout.html" %}

{% block body %}
    <div class="container mt-4 col-sm-6">
        <div class="card text-center">
            <div class="card-header">
                Add a new to-do
            </div>
            <div class="card-content my-4">
                <form action="{% url 'todolist:add' %}" method="post">
                    {% csrf_token %}
                    {{ addForm.as_p }}
                    <button type="submit" class="btn btn-success">Save</button>
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

todolist/templates/todolist/index.html
{% extends "todolist/layout.html" %}

{% block body %}
    <div class="container mt-4 col-sm-6">
        <div class="card text-center">
            <div class="card-header">
                To-do list
            </div>
            <div class="card-content">
                <ul class="list-group list-group-flush"></ul>
                    {% for todo in todos  %}               
                        <li class="list-group-item">{{ todo.content }}
                            <a class="btn btn-danger" href="{% url 'todolist:delete' todo.pk %}">Delete</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="card-footer">
                <a class="btn btn-success" href="{% url 'todolist:add' %}">Add todo</a>
            </div>
        </div>
    </div>
{% endblock body %}

todolist/templates/todolist/layout.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Celery</title>
</head>
<body class="bg-dark">

    {% block body %}
    {% endblock body %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</body>
</html>